vich_uploader:
    db_driver: orm

    mappings:
        user_profil:
            uri_prefix: /image/profil
            upload_destination: '%kernel.project_dir%/assets/image/profil'
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
